Missing RAILS_ENV=production and bundle exec
If you're omitting RAILS_ENV and `bundle exec` you'll have:

~~~
rake aborted!                             
NameError: uninitialized constant Annotate
[…]
~~~